Add Traefik deployment instructions
retaildevcrews/ocw-asb pull request #12
Opened 2021-05-11 03:43 UTC by kforeverisback

## Issues Closed or Referenced

- Closes https://github.com/retaildevcrews/OCW/issues/36
- Closes https://github.com/retaildevcrews/OCW/issues/76

# Type of PR

- [X] Documentation changes
- [ ] Code changes

## Purpose of PR
Traefik deployment instruction added in `ocw.md`

Added configuration (namespace, RoleBinding and URL prefix middleware) specific to NGSA workload

## Does this introduce a breaking change

- [ ] YES
- [X] NO

2021-05-11 04:08 UTC, bartr commented on ocw.md
> +# Create the ngsa Ingress object
shouldn't this use ngsa-ingress.$TEAM_NAME.yaml?

2021-05-11 04:08 UTC, bartr commented on ocw.md
> +
seems like we should be using GitOps to deploy this?

2021-05-11 04:10 UTC, bartr commented on deploy/ngsa-ingress.yaml
> +apiVersion: networking.k8s.io/v1
this should be deployed via GitOps

2021-05-11 05:16 UTC, jofultz commented on ocw.md
> +kubectl create -f workload/traefik.yaml
GItOps?

2021-05-11 05:39 UTC, jofultz requested changes
Review comments by myself and Bart.  I think the target is to generate the proper version of the file and then use GitOps to deploy.  If there's a reason we shouldn't let's discuss.  Also, we should have a brief chat on whether or not to maintain the "a0008" namespace or create something more relevant.

2021-05-11 05:41 UTC, bartr commented on ocw.md
> +echo $KEYVAULT_NAME
use this to get the user object ID - upn doesn't work on all accounts (like mine)

--object-id $(az ad signed-in-user show --query objectId -o tsv)

2021-05-11 05:41 UTC, bartr commented on ocw.md
> +az keyvault delete-policy --upn $(az account show --query user.name -o tsv) -n $KEYVAULT_NAME
--object-id $(az ad signed-in-user show --query objectId -o tsv)

2021-05-11 05:43 UTC, bartr commented on ocw.md
> +curl -ik -H "Host: ${AKS_HOSTNAME}" https://${AKS_PIP}/memory/version
I get a 502 gateway error on a clean deploy

2021-05-11 05:47 UTC, bartr commented on ocw.md
> +# Create the ngsa Ingress object
the ocw folder in GitOps doesn't have any ingress setup, so I don't think this will work

https://github.com/retaildevcrews/gitops/blob/main/ocw/ngsa-memory.yaml

2021-05-11 05:49 UTC, bartr commented on deploy/ngsa-ingress.yaml
> +      - bu0001a0008-00.aks-ingress.contoso.com
can this just be bu0001a0008-00.aks-ingress.aks-sb.com?

Does it need to change for team1.contoso.com?

2021-05-11 05:50 UTC, bartr commented on ocw.md
> +kubectl get ns a0008 -w
remove the -w for consistency with the rest of the guide

2021-05-11 05:50 UTC, bartr commented on ocw.md
> +kubectl wait -n a0008 --for=condition=ready pod --selector=app.kubernetes.io/name=traefik-ingress-ilb --timeout=90s
use k get po for consistency

2021-05-11 05:53 UTC, bartr commented on workload/traefik.yaml
> +        namespaces = ["a0008", "ngsa"]
we should add tiny to the namespaces

2021-05-11 19:04 UTC, kforeverisback reviewed
We changed the probe endpoint to `/memory/version` in `cluster-stamp.json` file.
In that way we won't have to deploy aspnetapp for application gateway to work.

2021-05-11 22:32 UTC, kforeverisback commented on workload/traefik.yaml
> +        namespaces = ["a0008", "ngsa"]
@bartr I didn't see any namespace named `tiny`. If we want to deploy an app and expose that via ingress, we can add the namespace.

2021-05-12 00:18 UTC, bartr commented on workload/traefik.yaml
> +        namespaces = ["a0008", "ngsa"]
we have a workload we deploy on the akdc clusters to the tiny namespace

2021-05-12 00:18 UTC, bartr approved these changes

2021-05-12 06:00 UTC, bartr approved these changes

2021-05-12 06:07 UTC, jofultz approved these changes

2021-05-12 06:15 UTC, merged