Updates to autogitops challenge instructions (path fixes, seds)
retaildevcrews/ocw-asb pull request #17
Opened 2021-05-12 23:12 UTC by PurpleBriar

## Issues Closed or Referenced

- Closes #135

# Type of PR

- [x] Documentation changes
- [x] Code changes
- [ ] Test changes
- [x] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

2021-05-12 23:18 UTC, bartr requested changes
The challenge doc should be an overview, not step-by-step instructions.

We don't have time to test these instructions before freeze.

2021-05-12 23:19 UTC, bartr commented on challenges/gitops/README.md
>  - [gitops](https://github.com/retaildevcrews/gitops)
should the directory name be `AutoGitOps`?

2021-05-12 23:21 UTC, bartr commented on challenges/gitops/README.md
> +The variable $ASB_TEAM_NAME is used throughout these instructions to reference a unique identifier or suffix used by your team. Execute all steps from the `challenges/gitops` directory of this reposi
this file should be in the gitops repo under /deploy/[target]

2021-05-12 23:22 UTC, AAkindele commented on challenges/gitops/templates/config.json
> +    "host": "bu0001a0008-00.<<TEAM_NAME>>.aks-sb.com",
If this is for the ingress, it'll be `<<TEAM_NAME>>.aks-sb.com` because of the latest changes to the main branch.

2021-05-12 23:22 UTC, bartr commented on challenges/gitops/templates/flux.yaml
> +apiVersion: v1
why not provide instructions for editing?

with this approach, we have to updated flux.yaml in two locations.

2021-05-12 23:23 UTC, PurpleBriar commented on challenges/gitops/README.md
> +The variable $ASB_TEAM_NAME is used throughout these instructions to reference a unique identifier or suffix used by your team. Execute all steps from the `challenges/gitops` directory of this reposi
The config. json file will be placed in the gitops repo after they update it

2021-05-12 23:23 UTC, bartr commented on challenges/gitops/templates/flux.yaml
> +        - --git-path=cluster-manifests,deploy/test
this won't work - cluster-manifests is our old yaml

2021-05-12 23:24 UTC, bartr commented on challenges/gitops/templates/flux.yaml
> +        - --git-branch=main
deploy/test should be deploy/their target name

2021-05-12 23:26 UTC, PurpleBriar commented on challenges/gitops/README.md
>  - [gitops](https://github.com/retaildevcrews/gitops)
> should the directory name be `AutoGitOps`?

I've updated it.

2021-05-12 23:28 UTC, PurpleBriar commented on challenges/gitops/templates/flux.yaml
> +        - --git-path=cluster-manifests,deploy/test
> this won't work - cluster-manifests is our old yaml

Should I ask them to copy the gitops folder over to the gitops repo instead?

2021-05-12 23:32 UTC, PurpleBriar commented on challenges/gitops/templates/config.json
> +    "host": "bu0001a0008-00.<<TEAM_NAME>>.aks-sb.com",
I've updated the json file. Thanks

2021-05-12 23:59 UTC, PurpleBriar commented on challenges/gitops/templates/flux.yaml
> +apiVersion: v1
I re4moved the template and added instructions

2021-05-13 02:48 UTC, bartr commented on challenges/autogitops/templates/config.json
> +{
this file should be in the rdc/gitops repo

2021-05-13 02:50 UTC, bartr commented on challenges/autogitops/README.md
> +### Setup Flux
you need to reset your cluster if you have already deployed the work load

2021-05-13 02:50 UTC, bartr commented on challenges/autogitops/README.md
> +Ensure that you have access to the gitops repositories listed below. You will need to be able to create branches and merge into main.
they will need to request access to the repos

2021-05-13 02:51 UTC, bartr commented on challenges/autogitops/README.md
> +The variable $ASB_TEAM_NAME is used throughout these instructions to reference a unique identifier or suffix used by your team. Execute all steps from the `challenges/gitops` directory of this reposi
challenges/autogitops

2021-05-13 02:52 UTC, bartr commented on challenges/autogitops/README.md
> +    "region": "[YOUR REGION]",  # SHOULD BE A VALID AZURE REGION
all of the clusters are deployed in eastus2

2021-05-13 02:53 UTC, bartr commented on challenges/autogitops/README.md
> +    "template": "ngsa-memory-ocw.yaml",
this template needs to be created

2021-05-13 02:53 UTC, bartr commented on challenges/autogitops/README.md
> +    "urlprefix": "/memory",
they will also need an ingress file

2021-05-13 02:54 UTC, bartr commented on challenges/autogitops/README.md
> +- Create a directory with your team name ($ASB_TEAM_NAME) in the [gitops deploy](https://github.com/retaildevcrews/gitops/tree/main/deploy) directory of the gitops repository
the contents of the GitOps folder (except ngsa) will need to be copied to rdc/gitops (only once)

2021-05-13 02:55 UTC, bartr commented on challenges/autogitops/README.md
> +- Copy the folders [baseline](../../gitops/baseline) and [ingress](../../gitops/ingress) to the $ASB_TEAM_NAME directory
these should be a shared directory except for the one ingress file that changes

2021-05-13 02:55 UTC, bartr commented on challenges/autogitops/README.md
> +    "imageName": "ghcr.io/retaildevcrews/ngsa-app",
ghcr.io won't work - has to be retaildevcrew/ngsa-app:beta

2021-05-13 02:56 UTC, bartr commented on challenges/autogitops/README.md
> +  }
we're not using pre-*
we should remove for clarity (there's a task on the board)

2021-05-13 02:57 UTC, bartr commented on challenges/autogitops/README.md
> +  - If `$ASB_TEAM_NAME` is not listed as a target, add it to the end of the list, and check in your updates. When your updates are merged into the main branch, it will trigger a workflow that will ge
this could be confusing and hackers could use the literal value instead of myTeamName

2021-05-13 02:57 UTC, bartr commented on challenges/autogitops/README.md
> +- Update `--git-path` to your deploy folder `deploy\$ASB_TEAM_NAME`
this should be the actual value, not the env var

2021-05-13 14:30 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +    "template": "ngsa-memory-ocw.yaml",
It's already in the autogitops repo

2021-05-13 14:43 UTC, PurpleBriar commented on challenges/autogitops/templates/config.json
> +{
The team will place this file in their directory in the rdc/gitops repository after they customize it.

2021-05-13 14:44 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +Ensure that you have access to the gitops repositories listed below. You will need to be able to create branches and merge into main.
Updated to ask the team to request access

2021-05-13 14:44 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +The variable $ASB_TEAM_NAME is used throughout these instructions to reference a unique identifier or suffix used by your team. Execute all steps from the `challenges/gitops` directory of this reposi
Updated.

2021-05-13 14:49 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +- Copy the folders [baseline](../../gitops/baseline) and [ingress](../../gitops/ingress) to the $ASB_TEAM_NAME directory
PR submitted for these changes

2021-05-13 14:50 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +    "region": "[YOUR REGION]",  # SHOULD BE A VALID AZURE REGION
Updated

2021-05-13 14:51 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +    "urlprefix": "/memory",
The ingress resource is already part of the template ngsa-memory-ocw.yaml

2021-05-13 14:52 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +- Create a directory with your team name ($ASB_TEAM_NAME) in the [gitops deploy](https://github.com/retaildevcrews/gitops/tree/main/deploy) directory of the gitops repository
PR submitted for this update. I initially had each team copying them over.

2021-05-13 14:53 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +  - If `$ASB_TEAM_NAME` is not listed as a target, add it to the end of the list, and check in your updates. When your updates are merged into the main branch, it will trigger a workflow that will ge
Updated

2021-05-13 14:58 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +- Update `--git-path` to your deploy folder `deploy\$ASB_TEAM_NAME`
Updated

2021-05-13 15:12 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +  }
Updated

2021-05-13 15:34 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +### Setup Flux
Added a note in the introduction

2021-05-13 15:57 UTC, PurpleBriar commented on challenges/autogitops/README.md
> +    "imageName": "ghcr.io/retaildevcrews/ngsa-app",
Updated

2021-05-13 17:33 UTC, AAkindele approved these changes

2021-05-13 19:56 UTC, bartr commented
Closed due to timing

2021-05-13 19:56 UTC, closed without merging